version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: console.log('test')

deployment:
  staging:
    branch: dev
    codedeploy:
      jupiterandthegiraffe:
        application_root: /
        region: eu-west-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: my-bucket
            key_pattern: jupiterandthegiraffe-{BRANCH}-{SHORT_COMMIT}
        deployment_group: my-deployment-group

