version: 2
jobs:
  test:
    branches:
      only:
        - master
        - dev
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: console.log('test')
#  development:
#    docker:
#      - image: fakesamgregory/jupiterandthegiraffe:<version TAG>
#      - image: fakesamgregory/jupiterandthegiraffe:latest
#        auth:
#          username: fakesamgregory  # can specify string literal values
#          password: $DOCKERHUB_PASSWORD  # or project UI env-var reference
  deployment:
    staging:
      branch: dev
      codedeploy:
        jupiterandthegiraffe:
          application_root: /
          region: us-west-1
          revision_location:
            revision_type: S3
            s3_location:
              bucket: jupiterandthegiraffe
              key_pattern: jupiterandthegiraffe-{BRANCH}-{SHORT_COMMIT}
