vm_settings: &vm_settings
  working_directory: ~/app
  docker:
    - image: circleci/node:10.9.0-browsers

version: 2
jobs:
  build_deploy_dev:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: sudo npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy Severless
          command: npm run build

      - run:
          name: AWS Sync
          command: aws --region eu-west-1 s3 sync ./dist s3://jupiterandthegiraffe.com/ --acl public-read --exact-timestamps --delete || return 1

  build_deploy_prod:
    <<: *vm_settings
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: sudo npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Serverless CLI and dependencies
          command: sudo npm i -g serverless

      - run:
          name: Deploy Severless
          command: npm run build:serverless:deploy

  test:
    <<: *vm_settings
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: sudo npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

      - build:
          requires:
            - test
          filters:
            branches:
              ignore: master

  build_and_deploy_dev:
    jobs:
      - test:
          filters:
            branches:
              only: master

      - build_deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master

  build_and_deploy_prod:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - hold:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - build_deploy_prod:
          requires:
            - hold
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

