vm_settings: &vm_settings
  working_directory: ~/app
  docker:
    - image: circleci/node:10.9.0-browsers

version: 2
jobs:
  build:
    <<: *vm_settings
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "ad:0e:95:93:e1:40:dc:60:d2:5e:58:b1:4a:64:18:e7"

      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.ssh
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

      - run: sh ./deploy.sh

  test:
    <<: *vm_settings
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: yarn run lint

      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
